### ISSUE TITLE
Change white backgrounds of demo SVGs to off-white

### ISSUE THREAD

**Issue by jdm** [servo/pathfinder#144]
According to Magic Leap contacts, bright white stresses the optics of the headset in ways that reduce performance. Changing any demos that involve bright white to an off-white colour instead should make the demo even better.

**Comment by jdm** [comment]
@asajeffrey Is this something you could address?

**Comment by asajeffrey** [comment]
Sigh, I guess so.

**Comment by pcwalton** [comment]
We could also fix this automatically if necessary, by going through the color palette on the Scene and dimming colors as needed.
