### ISSUE TITLE
Incorrect rendering and poor performance on some MPVG samples

### ISSUE THREAD

**Issue by trishume** [servo/pathfinder#151]
<img width="1064" alt="Screen Shot 2019-05-15 at 5 14 32 PM" src="https://user-images.githubusercontent.com/887610/57810249-4cfafd00-7735-11e9-8a8a-3a4f2cc10f73.png">

1. Download the inputs from http://w3.impa.br/~diego/projects/GanEtAl14/
2. Run the demo in release mode with `paris-30k.svg`, `contour.svg` or `hawaii.svg` (Hawaii has only minor artifacts)
3. Rendering is incorrect and slow. It's also nondeterministic, with different artifacts showing each frame just from moving the mouse around without changing anything.

The included tiger demo and the other MPVG demos that don't use unsupported features seem to render correctly and at the same or better speed than MPVG at the sizes they quote in the paper. However the same 3 images with artifacts are the only ones that run 3-10x slower than MPVG. Granted the GPU they use has benchmark results like 7x better than the one I have.

The artifacts disappear when zooming in close enough. I'm guessing based on where it appears that it occurs when too many paths are in the same tile and the sorting messes up somehow.

Other minor issues:
- The `reschart.svg` background dissapears at many but not all view angles in 3D mode.
- The `boston.svg` ocean has some crack artifacts, ([like most renderers do but MPVG doesn't](http://w3.impa.br/~diego/projects/GanEtAl14/sample.html?boston))

I'm running a 2014 15" rMBP, artifacts and timings are basically the same between my Iris Pro and GT 750m.

**Comment by pcwalton** [comment]
Based on experience, I'm guessing that what's happening is that the fill vertex positions are exploding out of the tiles, resulting in massive overdraw. That's what explains the poor performance.

**Comment by pcwalton** [comment]
@trishume  Presumably the MPVG code only works on NVIDIA due to the CUDA dependency?

**Comment by trishume** [comment]
Yah but being clearer than I was in the original issue: I've never ran MPVG, I'm just comparing against the numbers in the paper that were on totally different hardware with a faster GPU. So the numbers being comparable for most samples actually probably means PF3 is notably faster.

**Comment by pcwalton** [comment]
Well…I'll believe it when I see it. :) I have a Surface Book 1 and can try to run MPVG there.

**Comment by danwilhelm** [comment]
![intersection-clip](https://user-images.githubusercontent.com/6137185/58451941-5e93bb80-80ca-11e9-9791-a61ad09c61ac.gif)

Some of the MPVG examples have backgrounds that do not render properly, as @trishume mentioned (e.g. boston, reschart). These seem to occur when the renderer attempts to handle an intersection with the viewport. As shown in the GIF, the clipped geometry it currently generates does not seem to be ideal.

A temporary workaround would be to always return `EdgeRelativeLocation::Inside` from `trivially_test_segment`. This seems to properly render all of the clipped portions, at the expense of doing a bit more work. (Always returning `EdgeRelativeLocation::Outside` also renders nicely, except that anything intersecting is completely removed.)

**Comment by pcwalton** [comment]
@danwilhelm Thanks for the investigation! I've filed #170 to track this separately.

**Comment by danwilhelm** [comment]
PS - I'm not sure it's completely fair to compare P3 timings with MPVG, since MPVG uses multisampling and sometimes multiple passes. I'd hence expect MPVG to be slower but higher quality.

That said, the paper does bring up a number of quality issues their SVGs test for that might be interesting visual test cases for P3. For example, I attached two images rendered by P3 showing artifacts and aliasing (Moire). Of course, I assume these are to be expected at least until Issue #142 .

![renderer_aliasing](https://user-images.githubusercontent.com/6137185/58454371-247ae780-80d3-11e9-9d42-4e96b1c4cd0e.png)

![renderer_artifacts](https://user-images.githubusercontent.com/6137185/58454388-2ba1f580-80d3-11e9-98f6-06943033287c.png)

**Comment by pcwalton** [comment]
It's interesting that they'd consider supersampling higher quality, as I generally consider analytic AA to have the higher quality—effectively 256xAA. There are some artefacts from analytic AA in edge cases (no pun intended), but for the vast majority of edges analytic AA is higher-quality.

**Comment by raphlinus** [comment]
There are a lot more factors to quality besides conflation artifacts. MPVG also gets gamma "correct" (but correct gamma is not always better, particularly around thin strokes), and has the option for fancier convolution kernels than box filtering. These things are particularly visible in the tiger's whiskers, but also as moire in the sample posted above. I'm actually not yet convinced by the argument for fancier convolution, as larger support can reduce edge sharpness; I think for font rendering in particular you want as much sharpness as you can get, and things like moire in resolution charts is artificial.

Quality is complicated and multifactoral. I'm thinking of writing a blog post / wiki on the topic.
