### ISSUE TITLE
PDF frontend

### ISSUE THREAD

**Issue by pcwalton** [servo/pathfinder#157]
It would be nice to use Pathfinder as the backend for a PDF renderer.

**Comment by s3bk** [comment]
I might look into that. I have created PDFs in Rust before, so not the worst precondition.

**Comment by s3bk** [comment]
Oh. I just realize "Pathfinder as a backend for a PDF renderer", not a PDF as a backend for Pathfinder.
Well, now there is one at https://github.com/s3bk/pathfinder/tree/pdf_export

**Comment by s3bk** [comment]
Okay. I can now convert the Tiger from SVG to PDF and PDF to SVG. PDF Fonts though are a nightmare.

**Comment by s3bk** [comment]
Some PDFs work. I have not figured out how symbol fonts work though.
![grafik](https://user-images.githubusercontent.com/48330868/60030847-5d938100-96ac-11e9-8036-25f40cdff76b.png)

**Comment by asajeffrey** [comment]
The symbol fonts might be caused by some fonts (e.g. cmsy) being bitmaps rather than type 1. There are ttf versions, e.g. https://ctan.org/tex-archive/fonts/cm/ps-type1/bakoma/ttf/ I don't know if your TeX installation can be persuaded to use them.

**Comment by s3bk** [comment]
This is an example. It is a Type1C font (Compact Font Format). Glyph 3 is very much defined and has a valid outline. However I can't get the glyph out of font-kit's Font
[font_F3.zip](https://github.com/servo/pathfinder/files/3324915/font_F3.zip)

**Comment by s3bk** [comment]
I managed to implement Type1 (PostScript, OpenType and CFF), Type2 (CFF) and TrueType (via stb-rusttype) in Rust. Stll has a lot of missing parts, but it can render a few PDFs so far.

**Comment by s3bk** [comment]
Progress report for those not on matrix:

- [x] PDF integration in demo
- [ ] merge my fork back
- [ ] fix text transformation

**Comment by pcwalton** [comment]
We have a PDF frontend now.
