### ISSUE TITLE
The usage of PFCanvasFontContextRef seems unclear

### ISSUE THREAD

**Issue by toolness** [servo/pathfinder#179]
Hello!  While attempting to update the Unity plugin to the latest Pathfinder master in https://github.com/toolness/pathfinder-unity-fun/pull/2, I had a bit of trouble working with the new font context struct, which was added to the C API in 9138e1e0bb0c0e45abb93a2d113415adaefb37ec. Some of this is probably due to my own noobishness to Rust, which I apologize for.

Anyhow, I'm wondering if `PFCanvasCreate` consumes the passed-in font context, in a similar way that e.g. `PFCanvasFillPath` consumes a path.  If so, I'm wondering if it should actually _clone_ the passed-in font context instead, since the point of separating out the font context was to not have to create one anew every frame (and to my knowledge, `PFCanvasCreate` needs to be called every frame). Or is Rust magically cloning it already somehow?  And on the other hand, if it _is_ consuming it and cloning isn't an option, should a comment be added indicating that it's being consumed, similar to the comments for e.g. `PFCanvasFillPath`?

I also noticed that `c_canvas_minimal.c` never calls `PFCanvasFontContextDestroy()`, which seems to imply that either `PFCanvasCreate` is indeed consuming the font context, or the font context is being leaked in that program.

**Comment by pcwalton** [comment]
The canvas font context is safe to clone. Notice that it just consists of a couple of atomically-reference-counted objects: https://github.com/servo/pathfinder/blob/master/canvas/src/lib.rs#L510

**Comment by toolness** [comment]
Cool!  But how is a C client supposed to clone it?  Should there be a `PFCanvasFontContextClone()` exposed to the C API?  Or should `PFCanvasCreate()` clone it transparently on its end?

**Comment by pcwalton** [comment]
@toolness I just added a `PFCanvasFontContextClone()` API.

**Comment by toolness** [comment]
Cool, thanks!  I guess I will close this now.
