### ISSUE TITLE
Nothing is displayed when running on Magic Leap One

### ISSUE THREAD

**Issue by tokufxug** [servo/pathfinder#186]
The following demo has been installed on Magic Leap One.
https://github.com/servo/pathfinder/releases

Installation succeeded and ran. But nothing is displayed.
My Magic Leap One is Lumin OS v0.96.0.

Thanks,

**Comment by pcwalton** [comment]
@asajeffrey Any idea what's going on?

**Comment by asajeffrey** [comment]
@tokufxug, are you running the PF Landscape or Immersive app?

Does `mldb log` show anything relevant?

**Comment by tokufxug** [comment]
@asajeffrey I have installed PathfinderDemo.mpk below.
https://github.com/servo/pathfinder/releases

When launched, it is launched as an Immersive app. The display of Leaper has more than ten seconds.
As time goes on, the Leaper disappears and then nothing happens.

mldb log can not be acquired.
By the way, have you confirmed the operation check with Lumin OS v 0.96.0?

Also, is there no need for explicit permission settings?

Thanks,

**Comment by asajeffrey** [comment]
Try launching the landscape app and see what happens.

Do you have the MLSDK installed? If so, mldb should be in `tools/mldb/mldb`. The log output might be useful in determining if the program's crashed.

**Comment by tokufxug** [comment]
Try launching the landscape app and see what happens.
I know that this application is not a landscape. I think it is immersive.

![Capture_000000](https://user-images.githubusercontent.com/323081/59036486-63c8d700-883d-11e9-9728-e48dfc1d661a.JPG)

How do you start it as a landscape app?
Log is acquired. After acquisition, I will pass the log.

Thanks,

**Comment by asajeffrey** [comment]
After you install the mpk, the app launcher should have two new entries "PF Immersive Demo" and "PF Landscape Demo".

**Comment by tokufxug** [comment]
I did not notice that the landscape application was installed.

PF Landscape Demo was successfully launched.
It seems that PF Immersive Demo starts when you click the box displayed on PF Landscape Demo, but there is no response when it is started.

**Comment by asajeffrey** [comment]
Okay, that's progress! I'm hoping the log will show what's going on.

**Comment by tokufxug** [comment]
The log was not output even if PF Immersive Demo was started.

**-- Start PF Landscape Demo**
06-06 22:54:28.211  1874     1 I NoTag   : Pathfinder initializing
06-06 22:54:28.211  1874     1 I Pathfinder Demo: Initializing
06-06 22:54:28.211  1874     1 I Pathfinder Demo: Initialized logging
06-06 22:54:28.236  1874     1 I Pathfinder Demo: Initialized gl
06-06 22:54:28.236  1874     1 I Pathfinder Demo: Initialized pf
06-06 22:54:28.236  1874     1 I NoTag   : Pathfinder initialized
06-06 22:54:29.250  1874     1 W Pathfinder Demo: Could not resolve a FuncIRI reference: clip1.
06-06 22:54:29.250  1874     1 W Pathfinder Demo: Could not resolve a FuncIRI reference: clip3.
06-06 22:54:29.250  1874     1 W Pathfinder Demo: Could not resolve a FuncIRI reference: clip4.
06-06 22:54:29.250  1874     1 W Pathfinder Demo: Could not resolve a FuncIRI reference: clip5.
06-06 22:54:29.250  1874     1 W Pathfinder Demo: Could not resolve a FuncIRI reference: clip6.
06-06 22:54:29.250  1874     1 W Pathfinder Demo: Could not resolve a FuncIRI reference: clip7.
**-- Click the box of PF Landscape Demo (It is a log of alert notification of start confirmation.)**
06-06 22:54:36.721  1874     1 I NoTag   : Dispatching svg/nba-notext.svg
**-- Start the immersive demo, the Leaper icon will appear, but it will disappear after a few tens of seconds. The log was not output.**

I confirmed in the mldb log, but please let me know if there is another command you want to execute.

Thanks,

**Comment by asajeffrey** [comment]
Hmm, so the landscape app is launching the immersive app, but it's not starting. Can you reboot your device and see if you're getting the same behaviour (including nothing from the immersive app in the log)?

**Comment by tokufxug** [comment]
The operation by checking the log so far is the operation after restarting Magic Leap One.
This mpk has been tested on Magic Leap One with Lumin OS v 0.96.0 installed on the mozira side, right?

**Comment by asajeffrey** [comment]
In the office now, so I could test on a device. I downloaded the .mpk and installed it, it works on my device, but that's Lumin OS v0.95.2. I'll update the OS and try again.

**Comment by asajeffrey** [comment]
OK, I updated the OS on my device, and I can confirm the issue. The app works with LuminOS v0.95 but not v0.96. Thanks for your report, and for your patience tracking it down. Hopefully the fix for v0.96 won't take too long.

**Comment by asajeffrey** [comment]
Tracking the issue down, it looks like LuminOS 0.96 now requires lifecycle initialization to happen before any other initialization (previously you could initialize in any order). Fixing this will hopefully not take too long.

**Comment by asajeffrey** [comment]
@tokufxug Can you try https://www.dropbox.com/s/ovxfj3ghwghg7xk/PathfinderDemo.mpk?dl=0 and see if that works at your end?

**Comment by asajeffrey** [comment]
The second preview release at https://github.com/servo/pathfinder/releases/tag/preview-2 should fix this problem.

**Comment by tokufxug** [comment]
@asajeffrey  I downloaded second preview and both Landscape and immersive worked properly.
Thanks,

**Comment by asajeffrey** [comment]
Thanks for helping us sort this out!
