### ISSUE TITLE
Consider using a JIT 

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/pathfinder#196]
Blend2D is a new 2D vector rendering engine in town, which despite it's earlyness, achieve impressive performance numbers.
Source :
https://blend2d.com/performance.html

This "next generation" renderer has most of its benefits from this optimization paradigm:
"Blend2D is a next generation 2D vector graphics engine written in C++. It features a built-in JIT compiler that generates high performance 2D pipelines at runtime, which are much faster than static pipelines used in today's 2D engines. Dynamic pipeline construction is the main difference between Blend2D and other 2D engines, and guarantees the highest possible throughtput by taking advantage of CPU extensions detected at runtime. Blend2D provides also a deferred and asynchronous rendering, which makes it seamless to integrate with event-based environments such as node.js and next generation UI toolkits."

So the goal of the issue is to evaluate the feasibility of applying JIT pipeline construction to pathfinder, potentially massively improving performance.

**Comment by pcwalton** [comment]
Pathfinder has the design decision of explicitly not compiling shaders at runtime, to avoid unpredictable overheads.
