### ISSUE TITLE
Missing rendering with text effects enabled

### ISSUE THREAD

**Issue by heftig** [servo/pathfinder#201]
![image](https://user-images.githubusercontent.com/204006/59944933-5b3fe580-9466-11e9-9de5-bb3a72d59619.png)

Enabling either **Gamma Correction** or **Subpixel AA** results in the top-left half of the view not being drawn.

pathfinder 1caad35b46a9b8ef16bb55fa171fd6dafbbf70e8
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.1.0
rust 1.35.0
Arch Linux

**Comment by pcwalton** [comment]
Should be fixed now. Thanks for the report!
