### ISSUE TITLE
Implement clipping by an Outline

### ISSUE THREAD

**Issue by s3bk** [servo/pathfinder#209]
for whatever reason, PDF allows setting any path as the clipping path. It can consist of multiple contours and contain cubic bezier curves.

**Comment by pcwalton** [comment]
Per discussion with @nical in Whistler I think the best way to do this would be to combine tile masks using MIN blending.

**Comment by s3bk** [comment]
implemented in https://github.com/servo/pathfinder/commit/677c607a8ca051524078e3a2be83659dfab726a9
