### ISSUE TITLE
Canvas: Don't set a minimum stroke thickness

### ISSUE THREAD

**Issue by s3bk** [servo/pathfinder#219]
Right now the line width is capped at HAIRLINE_STROKE_WIDTH=0.033. I ran into this when using a -5..5 as my overall scene size. Alternatively the it could be capped at HAIRLINE_STROKE_WIDTH / transform.scale().

**Comment by pcwalton** [comment]
Capping the stroke width at `HAIRLINE_STROKE_WIDTH / transform.scale()` is the right fix, I think.
