### ISSUE TITLE
Question: Unity Plugin

### ISSUE THREAD

**Issue by dgerding** [servo/pathfinder#237]
I can't seem to find the current code or status for the "unity plugin".  My goal is the lightest-weight steps to render a string to screen using pathfinder and a target font.  Any links or sugesstions appreciated.  

Note: I was able to get the Magic Leap demo running and the results are really cool.

Thanks,
Dave G

**Comment by jdm** [comment]
Potential answer: https://github.com/toolness/pathfinder-unity-fun/

**Comment by pcwalton** [comment]
Yes, @jdm is correct.

Closing this for now.
