### ISSUE TITLE
Opening some SVG files consumes 30+ GB RAM

### ISSUE THREAD

**Issue by Shnatsel** [servo/pathfinder#239]
When opening the following file in the demo app it consumes 30+ Gb RAM. I had to kill it because it has exhausted both my RAM and swap, so I don't know if it will render successfully if given enough memory.

https://inkscape.org/~inkscape/%E2%98%85about-screen-inkscape-092

Rendering the same file with resvg and cairo backend takes only 25Mb RAM.

Tested on commit 5d5d30346bf4703ba49244e85bcb8c6ed7df48e9

**Comment by Shnatsel** [comment]
Here is a simpler reproducing example from openclipart: 
[turtle_jurgen_gaeremyn_01.svg.zip](https://github.com/servo/pathfinder/files/3801002/turtle_jurgen_gaeremyn_01.svg.zip)

**Comment by RazrFalcon** [comment]
Stumbled on the same issue.

**Comment by pcwalton** [comment]
The turtle picture is fixed with 40377d657aaff537a9869698690779111d564716 and previous commits (though the gradients don't show up because the SVG frontend is incomplete).

**Comment by pcwalton** [comment]
The original test case no longer consumes a ton of RAM, though it doesn't render properly (which may just be because the SVG frontend is incomplete). Closing. Thanks for the bug report!

**Comment by Shnatsel** [comment]
A quick smoke tests on a small subset of OpenClipArt shows no other anomalous behavior. Nice!
