### ISSUE TITLE
pathfinder_simd's use of SSE4.1 seems somewhat unnecessary

### ISSUE THREAD

**Issue by thomcc** [servo/pathfinder#241]
I don't have strong opinions here, and if SSE4.1 is all you care about then feel free to close. That said:

- `_mm_round_ps` with `_MM_FROUND_TO_NEAREST_INT` should be the same as `_mm_cvtps_epi32` (note: 1 t) followed by `_mm_cvtepi32_ps` unless overflow is a concern. I don't know the relative performance here, though.
- `_mm_test_all_ones` and `_mm_test_all_zeros` seem to be usually used on the result of a packed comparison. Generally the way you'd do this is via testing the output of `_mm_movemask_ps`. Note that this doesn't answer the 'are all/no bits set' question, but for the result of a comparison you don't actually need that, and it's. I suspect this would perform better or equivalently, as the test_all_foo intrinsics already expand to a longer sequence of operations. That said, the API you offer here is arguably cleaner than it would be if you used movemask

I think these are the only operations using post SSE2 instructions. I could have missed something though.

EDIT: I missed that _mm_srlv_epi32 is used, which is AVX2, which renders this a bit moot I guess...

**Comment by thomcc** [comment]
Ah, I missed AVX usage of _mm_srlv_epi32 in `abs` (#238). That's entirely unnecessary, as you can just just `_mm_set1_epi32(0x7fff_ffff)`.

**Comment by pcwalton** [comment]
I agree, let's limit ourselves to SSE2.
