### ISSUE TITLE
No way to load fonts from memory with the c api?

### ISSUE THREAD

**Issue by moon-chilled** [servo/pathfinder#247]
The relevant function is `PFCanvasFontContextCreateWithFonts()`, which takes a pointer to an array of `FKHandleRef`s, but there is no way to create an `FKHandleRef`.

**Comment by VijithK** [comment]
I initially stumbled upon same question. Seems like there is a way, we need to build https://github.com/servo/font-kit, there are few C bindings to create FKHandleRef.

**Comment by moon-chilled** [comment]
Ahh, I see.

Leaving the issue open because IMO that should be documented better (any maintainer, feel free to close if you disagree).
