### ISSUE TITLE
Feature suggestion: Option for subpixel anti-aliasing for other paths, not just text

### ISSUE THREAD

**Issue by ad8e** [servo/pathfinder#255]
Paths and fills can also have subpixel AA applied. Since pathfinder calculates trapezoidal area coverage, my guess is that having different pixel centers should not cause color distortion, but I don't know.

**Comment by s3bk** [comment]
I would actually surprised if text and other paths are treated differently. I have not seen anything that marks the paths produced from text as such, so I don't think there is any difference.

**Comment by pcwalton** [comment]
Perhaps #261 is what you want? Subpixel AA is just a filter and could be attached to layers.

**Comment by ad8e** [comment]
Looks reasonable to me. I have no insight on this matter, but your solution looks better than my suggestion.
