### ISSUE TITLE
GLDevice never calls gl::DeleteTextures?

### ISSUE THREAD

**Issue by windexlight** [servo/pathfinder#264]
I feel like I must be missing something, but nowhere in the entire project do I find any calls to gl::DeleteTextures. Shouldn't GLTexture implement Drop like many of the other GL* types? Are textures freed implicitly somehow by freeing other resources? Is it just assumed that textures are only generated for global use for the life of the process, and left for the OS/driver to clean up after exit (or when the context is deleted)?

**Comment by pcwalton** [comment]
Yes, the textures should be deleted! Whoops.
