### ISSUE TITLE
Remaining features for HTML canvas support and first crates.io release

### ISSUE THREAD

**Issue by pcwalton** [servo/pathfinder#265]
We're not too far from full HTML canvas support. Remaining features:

* [x] Linear gradients
* [x] Radial gradients
* [x] Image patterns
* [x] Clips (#222)
* [x] Even-odd fill rule
* [x] `clearRect()`
* [x] Composite ops
* [x] Images with alpha applied
* [x] Image smoothing control
* [x] Image repeating
* [x] Blur for shadows (needs #261)
* [x] Radial gradients along a line

I think once we have complete HTML canvas support, we will be ready for a crates.io release.

Another remaining nice-to-have is Web platform tests. There are quite a few tests for HTML canvas and it would be nice to have them run in CI. The problem here, of course, is that these tests are in JavaScript, so we would need some way to port them…

**Comment by pcwalton** [comment]
We should be feature complete for HTML canvas features now. Let's open individual issues for anything else we need.

**Comment by Keavon** [comment]
> We should basically be feature complete for HTML canvas features now. Let's open individual issues for anything else we need.

Does being feature-complete with the HTML5 2D Canvas API mean that this statement in the project readme should be changed? (Specifically, "subset".)

> # Quick start
> Pathfinder contains a library that implements a subset of the HTML canvas API.
