### ISSUE TITLE
Clamp winding number to [-1, 1] when drawing an Outline

### ISSUE THREAD

**Issue by s3bk** [servo/pathfinder#266]
The following image shows a word made from joining the outlines of the individual glyphs into one and drawing with partially transparent paint.
<img width="512" alt="grafik" src="https://user-images.githubusercontent.com/48330868/74376433-2a486280-4df3-11ea-9f41-535a93205508.png">

**Comment by s3bk** [comment]
Actually a flag to set the preferred mode would be even better. (PDF allows this…)
- NonZero
- EvenOdd

**Comment by pcwalton** [comment]
This may be fixed now as part of the clip work.

**Comment by pcwalton** [comment]
Even-odd fill rule should be implemented as of 3ad1c25.

**Comment by s3bk** [comment]
I can confirm that it in fact working.
