### ISSUE TITLE
Scene in Scene embedding

### ISSUE THREAD

**Issue by s3bk** [servo/pathfinder#268]
Sometimes you want to draw an existing `Scene` as part of a bigger scene.

Currently I am doing this: 
```rust

    fn draw(&self, _ctx: &DrawCtx, origin: Vector2F, size: Vector2F, scene: &mut Scene) {
        // coorinates are at the lower left, but objects expect the origin at the top left
        let view_box = self.scene.view_box();
        let svg_size = view_box.size();
        let scale = size.x() / svg_size.x();
        let tr = Transform2F::from_translation(origin)
            * Transform2F::from_scale(Vector2F::splat(scale))
            * Transform2F::from_translation(-view_box.lower_left());
        
        for (paint, outline, _) in self.scene.paths() {
            let outline = outline.clone();
            let new_path = DrawPath::new(
                outline.transform(tr),
                scene.push_paint(paint),
                None,
                PaFillRule::Winding,
                BlendMode::default(),
                String::new());
            scene.push_path(new_path);
        }
    }
```

While this works, it would be nice to have something like
```rust
impl Scene {
    [...]
    fn push_scene1(&mut self, scene: &Scene, tr: &Transform2F);
    fn push_scene2(&mut self, scene: &Scene, tr: &Transform2F, clip_path: Option<ClipPathId>, blend_mode: BlendMode);
}
```
where `push_scene1` behaves as if the drawing operations used to create the embedded scene were called at this point, and `push_scene2` allows to clip the drawing operations and also control the blend mode.

Maybe it could even take `Arc<Scene>` and avoid copying the data.

**Comment by pcwalton** [comment]
Note that I just added `RenderTarget` support last night that allows you to render to a texture that you can then use as a `Paint`. This is how I want to handle nested scenes.

**Comment by s3bk** [comment]
I am not sure about a texture. Using a scene means that it will render properly under transformations, which is mostly what I do.

The user moves and zooms the viewport, in which pages are displayed. On a page there can be objects that are cached as a scene (in case of SVG). I would need to render objects and pages to a quite large texture to avoid interpolation artifacts, and then any edit to the page would throw that away.

A scene is basically a "free" way of caching an intermediate result in case it can be reused, or in the case of SVG to avoid parsing it each frame.
