### ISSUE TITLE
Set up a chat room on Matrix

### ISSUE THREAD

**Issue by pcwalton** [servo/pathfinder#274]
Let's go ahead and have a chat room. Matrix seems like a good choice here to follow Mozilla and Servo.

**Comment by s3bk** [comment]
While I would prefer Zulip, A matrix room will probably work too and is better than nothing.

**Comment by pcwalton** [comment]
There's now a Matrix room [`#pathfinder:mozilla.org`](https://matrix.to/#/!XiDASQfNTTMrJbXHTw:mozilla.org?via=mozilla.org).
