### ISSUE TITLE
nfd link error on Windows 

### ISSUE THREAD

**Issue by mnordine** [servo/pathfinder#276]
To reproduce:

`cd demo\native`
`cargo run --release`

result:

```
note: libnfd-6fb58101fd1ec5ca.rlib(nfd_win.o) : error LNK2019: unresolved external symbol __imp_SHCreateItemFromParsingName referenced in function "enum nfdresult_t __cdecl SetDefaultPath(struct IFileDialog *,char const *)" (?SetDefaultPath@@YA?AW4nfdresult_t@@PEAUIFileDialog@@PEBD@Z)
C:\Users\me\code\rust\pathfinder\target\release\deps\demo.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by BenGachowski** [comment]
It seems libnfd depends on nfd-sys, which explicitly states it does not support windows. It's no longer maintained and the last update was 4 years ago so I don't think its going get support either.

**Comment by pcwalton** [comment]
I built and ran the Pathfinder demo on Windows yesterday. Does this still happen?

**Comment by VijithK** [comment]
@pcwalton I tried Pathfinder demo on windows, even I had seen this issue before. I am not seeing nfd link issue now. Demo builds fine, it however fails for me while running with `error: process didn't exit successfully:demo.exe (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

**Comment by mnordine** [comment]
Sorry for the delay, yes, it does work here now. 👍

**Comment by pcwalton** [comment]
> 
> 
> @pcwalton I tried Pathfinder demo on windows, even I had seen this issue before. I am not seeing nfd link issue now. Demo builds fine, it however fails for me while running with `error: process didn't exit successfully:demo.exe (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)`

Please file a separate bug for this, attaching a stack trace and giving your system information if you can. (Unfortunately it's working for me so I can't do much with just that error message.)

**Comment by pcwalton** [comment]
> 
> 
> Sorry for the delay, yes, it does work here now. 👍

Great! Closing.
