### ISSUE TITLE
Should a closed path include an explicit line to origin?

### ISSUE THREAD

**Issue by inferiorhumanorgans** [servo/pathfinder#279]
Given:

```rust
let mut path = Path2D::new();
path.move_to(Vector2F::new(0.0, 1.1));
```

What should the path itself look like?

Currently we get:

```rust
assert_eq!("M 0 1 L 0 1 z", format!("{:?}", path.into_outline()));
```

But in reading the Mozilla docs it seems like `z` implies that last line to origin so that the following should be true:

```rust
assert_eq!("M 0 1 z", format!("{:?}", path.into_outline()));
```

**Comment by pcwalton** [comment]
This doesn't repro for me. Such a path has an empty outline and as such debugs as an empty string.

**Comment by pcwalton** [comment]
Oh, I see what you mean. Should be fixed now.
