### ISSUE TITLE
Random artifacts when rendering path (webgl)

### ISSUE THREAD

**Issue by zimond** [servo/pathfinder#284]
Use pathfinder's Path2D API and render some outlines into scene with webgl results with random artifacts (seems to be blank tiles).

<img width="336" alt="image" src="https://user-images.githubusercontent.com/4921289/76375465-e0668400-6380-11ea-952b-cf42c065362c.png">

As no one reported this before, I think maybe it's webgl related. @s3bk

**Comment by s3bk** [comment]
I have not seen this before… can you send me the scene as SVG?

**Comment by s3bk** [comment]
Time to implement Serialize and Deserialize for Scene… it would make sending Debug info a lot easier!

**Comment by zimond** [comment]
[test.svg.zip](https://github.com/servo/pathfinder/files/4317707/test.svg.zip)

here is the test svg. I managed to load this svg file in your webgl_demo project ( which uses a forked pathfinder). Even though no artifacts, I found that there are some glitch vertical lines.

![20200311180119](https://user-images.githubusercontent.com/4921289/76409144-f435d880-63c8-11ea-8277-f6b030d3e416.jpg)

Cannot compile `pathfinder_view` against latest server/pathfinder so I cannot provide a pathfinder rendered screenshot for this, sorry

**Comment by s3bk** [comment]
Yes, pathfinder_view doesn't work with servo/pathfinder yet. There are a few PRs to come.

I have seen the vertical lines before. I suspect it is a rounding error in the solid tile lookup

**Comment by s3bk** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/48330868/76410219-a1482b00-63a0-11ea-80c7-03aebcd14f75.png">
This is what it looks like when I convert the SVG into a PDF and drop it in https://pdf-rs.github.io/view-wasm/

**Comment by zimond** [comment]
I'll try to create a demo using servo/pathfinder and see if I can re-create the behavior

**Comment by s3bk** [comment]
I updated the webgl-demo, so you can now drop SVG files on it.

**Comment by zimond** [comment]
OK I find that the problem actually is `pathfinder_canvas`'s `Path2D`. Its `close_path()` API is missing an additional line segment to the first point in subpath. So the result is screwed up. LOL, I'm adding a patch to fix this problem

**Comment by pcwalton** [comment]
Pretty sure the lines are because the denominator is 65535 instead of 65536 in mask uvs. I'm going to just switch to floats.

**Comment by zimond** [comment]
@pcwalton @s3bk I managed to reproduce it when applying a negative scale transform to the scene. (Notice the little white block in the following screenshot)

<img width="102" alt="image" src="https://user-images.githubusercontent.com/4921289/76678224-f68a7380-6610-11ea-9270-6ea1e8576f1b.png">

Related code: https://github.com/zimond/test-pathfinder/blob/master/src/lib.rs#L79

**Comment by zimond** [comment]
any ideas? 😶

**Comment by s3bk** [comment]
No, but I can reproduce it now after merging from servo/pathfinder.

**Comment by pcwalton** [comment]
I couldn't reproduce this in the demo. Could you try again? Ubershaders significantly changed how rendering is done, so the issue might or might not be gone.

**Comment by s3bk** [comment]
In my test it is gone with ubershaders

**Comment by zimond** [comment]
It's indeed gone!
