### ISSUE TITLE
Switch tile shaders to an ubershader

### ISSUE THREAD

**Issue by pcwalton** [servo/pathfinder#287]
The number of shaders is being unwieldy. Per discussion with the Firefox graphics team I'm tentatively proposing that we switch to an ubershader that is then specialized on-the-fly into specific shaders via preprocessor magic when the shader graph is hot.

This should also improve performance by eliminating the need for temporary render targets in many cases. For example, the mask step can be entirely eliminated except in pathological cases (more nested clips than available samplers).

**Comment by s3bk** [comment]
Does this work on WebGL?

**Comment by pcwalton** [comment]
It should work just fine on WebGL.

**Comment by pcwalton** [comment]
Here is the node pipeline I'm envisioning:

      Mask UV 0         Mask UV 1
          +                 +
          |                 |
    +-----v-----+     +-----v-----+
    |           | MIN |           |
    |  Mask 0   +----->  Mask 1   +------+
    |           |     |           |      |
    +-----------+     +-----------+      v       +----------+     +-------------+
                                       Apply     |          |     |             |       GPU
                                       Mask +---->  Filter  +----->  Composite  +---->Blender
                                         ^       |          |     |             |
    +-----------+     +-----------+      |       +----------+     +-------------+
    |           |  ×  |           |      |
    |  Color 0  +----->  Color 1  +------+
    |           |     |           |
    +-----^-----+     +-----^-----+
          |                 |
    +-----+-----+           |
    |           |           |
    |  Radial   |           |
    | Gradient  |           |
    |           |           |
    +-----^-----+           |
          |                 |
          +                 +
      Color UV 0       Color UV 1

**Comment by s3bk** [comment]
So basically building the shader by putting building blocks together depending on the scene graph?

**Comment by pcwalton** [comment]
Depending on the clip/paint/filter/composite ops, yeah. But we only actually build a customized shader if a particular graph is used frequently (say, 100 or 1000 times). Otherwise we use a generic ubershader. This avoids compilation time unless it's really needed, and it also improves batching if a filter is only used a few times.

**Comment by jrmuizel** [comment]
FWIW, WebRender is moving to a world where we need to know the shader source at build time. This is for Software-WebRender and offline shader optimization for startup on Mac and Android.

That's not to say doing runtime shader generation is necessarily a bad idea in this context, (Skia does it after all) it just makes some things harder.

**Comment by pcwalton** [comment]
@jrmuizel So what I was envisioning is a bit of a compromise approach in which all the shader functions are handwritten, but the "main" function that glues everything together via function calls is dynamically generated. I was thinking that this should be reasonably compatible with SWWR and Metal-like "shader library" approaches. As long as all the important logic is precompiled into bytecode or GPU machine code, dynamically generating the final main function shouldn't be a problem, right?

**Comment by jrmuizel** [comment]
Yeah, that sounds reasonable. I don't know how well dynamically generating just part of it will work in practice, but none of the current motivations for ahead of time compilation directly apply to pathfinder anyways. The ubershader covers startup and there's not an immediate need for doing software pathfinder in a sw-wr style.
