### ISSUE TITLE
Use f32::abs to support negative scale factors

### ISSUE THREAD

**Issue by BenGachowski** [servo/pathfinder#298]
In the `Canvas` struct, the `stroke_path` function checks the current transform to determine if the stroke width is below a certain scale factor, but does not take into account the possibility of negative scales on the transform. This leads to strokes being rendered incorrectly when such a transform is used.

I have tested it using `f32::abs` on the matrix scale values, and can confirm it does fix the issue.

This is only if you want to support negative scale factors of course, if not I'd just put an assertion there instead.

**Comment by pcwalton** [comment]
Holy cow, I was *just* tracking this bug down in the NanoVG demo. Thank you!
