### ISSUE TITLE
canvas_minimal crashes due to missing tile_clip shader

### ISSUE THREAD

**Issue by nokola** [servo/pathfinder#301]
The `tile_clip` shader is not built into resources/shaders and causes runtime failures.

Environment: Windows 10
**Steps to reproduce:**
1. Setup SDL2 per instructions in readme.md for canvas_minimal
2. `cargo run` in canvas_minimal folder

**Expected:**
canvas loads and house shows up on screen

**Actual:** panic
**Potential fix:** 
1. Copy `shaders/tile_clip.vs.glsl` and `shaders/tile_clip.fs.glsl` into `resources/shaders/`
2. in `resources\MANIFEST` add:
```
shaders/gl3/tile_clip.fs.glsl
shaders/gl3/tile_clip.vs.glsl
```
Not sure why the shaders are separate in `shaders/` and `resources/shaders/` folders.
 
**Logs:**
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Kind(NotFound)', D:\Repos\GitHub\pathfinder\gl\src\lib.rs:718:47
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:77
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\mod.rs:1426
   5: std::sys_common::backtrace::_print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
   8: std::panicking::default_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:224
   9: std::panicking::rust_panic_with_hook
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
  10: std::panicking::begin_panic_handler
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
  11: core::panicking::panic_fmt
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\panicking.rs:85
  12: core::option::expect_none_failed
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\option.rs:1199
  13: core::result::Result<alloc::vec::Vec<u8>, std::io::error::Error>::unwrap<alloc::vec::Vec<u8>,std::io::error::Error>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\result.rs:963
  **14: pathfinder_gl::{{impl}}::create_shader
             at D:\Repos\GitHub\pathfinder\gl\src\lib.rs:718**
  15: pathfinder_gpu::Device::create_program_from_shader_names<pathfinder_gl::GLDevice>
             at D:\Repos\GitHub\pathfinder\gpu\src\lib.rs:113
  16: pathfinder_gpu::Device::create_program<pathfinder_gl::GLDevice>
             at D:\Repos\GitHub\pathfinder\gpu\src\lib.rs:120
  17: pathfinder_renderer::gpu::shaders::ClipTileProgram<pathfinder_gl::GLDevice>::new<pathfinder_gl::GLDevice>
             at D:\Repos\GitHub\pathfinder\renderer\src\gpu\shaders.rs:457
  18: pathfinder_renderer::gpu::renderer::Renderer<pathfinder_gl::GLDevice>::new<pathfinder_gl::GLDevice>
             at D:\Repos\GitHub\pathfinder\renderer\src\gpu\renderer.rs:172
  19: canvas_minimal::main
             at .\src\main.rs:49
  20: std::rt::lang_start::{{closure}}<()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
  21: std::rt::lang_start_internal::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
  22: std::panicking::try::do_call<closure-0,i32>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:305
  23: panic_unwind::__rust_maybe_catch_panic
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
  24: std::panicking::try
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:281
  25: std::panic::catch_unwind
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panic.rs:394
  26: std::rt::lang_start_internal
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:51
  27: std::rt::lang_start<()>
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
  28: main
  29: invoke_main
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  30: __scrt_common_main_seh
             at d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  31: BaseThreadInitThunk
  32: RtlUserThreadStart

**Comment by pcwalton** [comment]
Oops! Sorry about that.

**Comment by nokola** [comment]
Awesome, thanks for the extremely fast fix!
