### ISSUE TITLE
Crash on call to `pathfinder_canvas::Path2d::rect`

### ISSUE THREAD

**Issue by derekdreery** [servo/pathfinder#307]
~~I ran the glutin pathfinder canvas example, and got the following error when calling `Path2d::rect(RectF::new(Vector2F::new(150.0, 110.0), Vector2F::new(750.0, 140.0))`:~~

I ran the glutin pathfinder canvas example, and got the following error when calling `Path2d::move_to(Vector2F::new(150.0, 110.0))` followed by `Path2d::rect(RectF::new(Vector2F::new(150.0, 110.0), Vector2F::new(750.0, 140.0))`.

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/pathfinder_content-0.5.0/src/outline.rs:586:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/pathfinder_renderer-0.5.0/src/concurrent/scene_proxy.rs:143:27
```

**EDIT** The cause was incorrect, and was changed to the actual cause.

**Comment by derekdreery** [comment]
Is this relevant?

https://github.com/servo/pathfinder/blob/84bf4341c253ae36756d27671a17cb44d59cd250/canvas/src/lib.rs#L660

**Comment by pcwalton** [comment]
This works for me:

    let mut path = Path2D::new();
    path.move_to(vec2f(150.0, 110.0));
    path.rect(RectF::new(vec2f(150.0, 110.0), vec2f(750.0, 140.0)));

Could you paste the rest of your code?

**Comment by pcwalton** [comment]
Closing for now, but feel free to reopen with a small test case if you continue to run into this issue :)
