### ISSUE TITLE
request adding pub scene ref to struct Canvas/CanvasRenderingContext2D

### ISSUE THREAD

**Issue by colorhook** [servo/pathfinder#308]
Code from example in this repo:

```rust
fn render(&mut self) {
  ...
 // Make a canvas.
 let mut canvas =    
    Canvas::new(self.drawable_size.to_f32()).get_context_2d(self.font_context.clone());
 canvas.set_line_width(CIRCLE_THICKNESS * self.device_pixel_ratio);
 canvas.set_stroke_style(FillStyle::Color(foreground_color.to_u8()));
 canvas.set_global_alpha(0.75);
  ...
}
```

Is this necessary to create a totally new canvas instance in each render loop?

The `CanvasRenderingContext2D` has `current_state` and `saved_states`, how to record the state across the frames?

The `Scene` struct is cloneable, so add method for `CanvasRenderingContext2D`  to acquire the state ref maybe a solution:

```rust
let scene = canvas.scene().clone();
let executor = SceneProxy::from_scene(scene, RayonExecutor);
executor.build_and_render(&mut renderer, BuildOptions::default());
```

**Comment by s3bk** [comment]
This isn't trivial and not really how the canvas API is supposed to be (mimics the HTML Canvas).

Maybe you want a somewhat different API?
I ended up building my own layer on top of pathfinder: https://github.com/s3bk/vector/blob/master/src/lib.rs

**Comment by colorhook** [comment]
mimics the HTML Canvas, the canvas can be paint always. if 'canvas.toDataURI()` invoked, the canvas context is useful for drawing later.

But if `canvas.into_scene()` called in `pathfinder`, the canvas and context were disposed.

**Comment by pcwalton** [comment]
I think what we really want is for the canvas object and `CanvasRenderingContext2D` to be separate, like they are in the HTML API.

**Comment by colorhook** [comment]
`rust-skia` is a good choice for implementing canvas binding with deno.

In Javascript, I can create a `Canvas` instance by custom Canvas constructor 

```javascript
const {
  op_canvas_create
} = Deno.core.ops();

class OffscreenCanvas extends EventTarget {
  #rid = null;
  constructor(width, height) {
    super();
    const zero_copy_buffer = Deno.core.dispatch(op_canvas_create, { width, height });
    this.#rid = JSON.parse(Deno.core.decode(zero_copy_buffer)).rid;
  }
}
```

And in the Rust side, there should be a `Canvas` instance corresponding to:

```rust
pub fn init(i: &mut CoreIsolate, s: &State) {
  i.register_op("op_canvas_create", s.stateful_json_op2(op_canvas_create));
}

#[derive(Deserialize)]
struct CanvasCreateArgs {
  width: i32,
  height: i32,
}
pub fn op_canvas_create(
  isolate_state: &mut CoreIsolateState,
  _state: &State,
  args: Value,
  _data: &mut [ZeroCopyBuf],
) -> Result<JsonOp, OpError> {
  let args: CanvasCreateArgs = serde_json::from_value(args)?;
  let resource_table = isolate_state.resource_table.clone();
  let mut resource_table = resource_table.borrow_mut();
  let surface = Surface::new_raster_n32_premul((args.width, args.height)).expect("no surface!");
  let rid = resource_table.add(
    "canvas",
    Box::new(surface),
  );
  let json_res = json!({
    "rid": rid
  });
  Ok(JsonOp::Sync(json_res))
}
```

The Deno ResourceTable owner the Surface and Canvas instance, and their lifetime not affected while rending or bitmap retrieved.

But it's difficult in `pathfinder` before. I need call `canvas.into_scene()` before rendering, so the canvas ownership moved. 

And I got a new method `scene()` in `Canvas` in the lastest repo, Maybe it's useful because the Canvas ownership would keeping while frame ticking, I will try it later.
