### ISSUE TITLE
glsl shader compilation fails on AMD/win10

### ISSUE THREAD

**Issue by hardiesoft** [servo/pathfinder#309]
It seems to be choking on the precision statements:
`
precision highp float;
precision highp sampler2D;
`
If I remove these from all the glsl files they compile properly, so seems like AMD radeon glsl validation might be a little over-zealous?

**Comment by pcwalton** [comment]
What if you just remove `precision highp sampler2D`?

The [OpenGL wiki](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Precision_qualifiers) says that only `float` and `int` are supported in OpenGL (not ES).

**Comment by hardiesoft** [comment]
Yes, just disabling the `precision highp sampler2D` lines works.
