### ISSUE TITLE
Rendering nothing should still paint background

### ISSUE THREAD

**Issue by sunjay** [servo/pathfinder#318]
I'm using the `canvas_glutin_minimal` example as a starting point for a renderer. I noticed that if all the calls to canvas methods (see snippet below) are removed or commented out, the renderer does nothing. It doesn't even paint the background, so a black screen is displayed even if a non-black background color is set.

![blank window](https://user-images.githubusercontent.com/530939/81114925-e6945f00-8ef0-11ea-949a-f0cf63855525.png)

This is troublesome for me because there is a state in my application where nothing has been drawn yet. Even calling `clear_rect` doesn't actually result in the background being painted.

This snippet shows the calls I commented out to get the image above:

https://github.com/servo/pathfinder/blob/c7ce2153de7dc5f1d095aeb1f88676176102ef69/examples/canvas_glutin_minimal/src/main.rs#L63-L78

I would really appreciate it if pathfinder could paint the background even when there are no primitives to draw. This is pretty common behaviour and would be a very useful default.

## Version Info

```rust
$ rustc --version --verbose
rustc 1.43.0 (4fb7144ed 2020-04-20)
binary: rustc
commit-hash: 4fb7144ed159f94491249e86d5bbd033b5d60550
commit-date: 2020-04-20
host: x86_64-unknown-linux-gnu
release: 1.43.0
LLVM version: 9.0
```

In my application I'm using version v0.5 of pathfinder which is published on crates.io. The git commit used to generate the image above is shown below.

```
$ git log -1
commit c7ce2153de7dc5f1d095aeb1f88676176102ef69 (HEAD -> master, origin/master, origin/HEAD)
Merge: a373a1fb f8405d81
Author: Patrick Walton <pcwalton@mimiga.net>
Date:   Tue May 5 13:11:06 2020 -0700

    Merge pull request #316 from pcwalton/reduce-buffer-size
    
    Reduce the size of buffers for performance
```

## Workaround

My current workaround for this is to paint a 1 px rectangle in the corner of the window:

```rust
// Need to render *something* every time to get pathfinder to even render a background
canvas.stroke_rect(RectF::new(vec2f(0.0, 0.0), vec2f(1.0, 1.0)));
```

**Comment by pcwalton** [comment]
Yeah, this is because modern GPU APIs like Metal don't have the concept of a clear action that's different from a rendering action, so when rendering is removed then clear is as well. I'll go ahead and add a special clear pass for this case, as it also impacts my pure-GPU branch as well.

**Comment by sunjay** [comment]
Thank you!
