### ISSUE TITLE
OpenGL Timer Queries Slowdown

### ISSUE THREAD

**Issue by as-cii** [servo/pathfinder#360]
While testing how quickly pathfinder can re-render a whole scene using the OpenGL backend, I noticed some suspicious slowdowns (~ 700ms) that were occurring intermittently (but quite consistently) when using the integrated GPU (note that these wouldn't show up in `Instruments.app` when recording my application with a time profiler). 

After adding some logging to both pathfinder and my own code, I noticed that the slowdowns were coming from the `DrawTiles` command and, more specifically, I tracked them down to calls to `Device::begin_timer_query(&timer_query)`. Given that this call (and its `end_timer_query` counterpart) seemed to be just debug tools, I went ahead and commented out their implementation (i.e., `gl::BeginQuery(TIME_ELAPSED)` and `gl::EndQuery(TIME_ELAPSED)`). This seemingly fixed the problem and the application always renders smoothly without dropping a frame.

For what it's worth, I also collected some measurements using two different configurations:

- Using the discrete GPU. No noticeable slowdowns there, everything seemed to work smoothly.
- Using the Metal backend. Everything worked perfectly there as well.

I am unclear on what conclusions to draw from here given my little familiarity with the codebase, but there would seem to be something odd going on with the OpenGL backend/driver. I'd be more than happy to help investigate this further with some guidance and/or give you access to the closed-source application as well.

/cc: @nathansobo

###### Pathfinder Version
0f3500921596bdb2924d7bd62c4f983afc9332ec (it's actually a [fork](https://github.com/nathansobo/pathfinder/tree/zed) of that commit, but it deviates very slightly from it and disables the problematic timer queries illustrated above)

###### Operating System
macOS Catalina 10.15.4

###### Laptop
MacBook Pro 15" 2019

###### Integrated GPU
Intel UHD Graphics 630

###### Discrete GPU
Radeon Pro 560X

**Comment by s3bk** [comment]
This can probably be "solved" by putting timer queries behind a config attribute…
Why spend time looking for the time when the application doesn't care anyway.

**Comment by pcwalton** [comment]
Interesting, good catch. I'll make them optional if the debug UI is off.
