### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by yaxinlx** [servo/pathfinder#375]
```
$ cargo run --example canvas-glutin-minimal --release
error: no example target named `canvas-glutin-minimal`
```

Sorry, this is a newbie question.

**Comment by shahreel** [comment]
cargo run --bin canvas_glutin_minimal --release

**Comment by yaxinlx** [comment]
It woks! Thanks very much for your help.

But why the following one doesn't work to run the `demo/native` demo?
```
cargo run --bin native --release
```

**Comment by shahreel** [comment]
The app is named demo. Try run:
<pre>cargo run --bin demo --release</pre>

**Comment by yaxinlx** [comment]
Many thanks for you help!

So the bin names are retrieved from Cargo.toml files. It is not intuitive sometimes.
