### ISSUE TITLE
New SPIR SPV_INTEL_vector_compute extension

### ISSUE THREAD

**Issue by LifeIsStrange** [servo/pathfinder#415]
https://www.phoronix.com/scan.php?page=news_item&px=Intel-IGC-Vector-Backend

https://github.com/intel/llvm/pull/1612/files

This could revolutionize 2D rendering performance (and/or efficiency) on Intel igpus (most of the market) so you should keep an eye on it :}

**Comment by pcwalton** [comment]
Interesting. Closing for now as not enough information is yet available to see if this will be useful for PF.
