### ISSUE TITLE
Image::new is very slow

### ISSUE THREAD

**Issue by colorhook** [servo/pathfinder#447]
```
let start = std::time::Instant::now();
pixels.hash(&mut pixels_hasher);
let delta = std::time::Instant::now() - start;
println!("image pixels.hash cost: {}ms", delta.as_micros() as f32 / 1000.0);
```

In release version:

```
output:  image pixels.hash cost: 20.289ms
```

**Comment by s3bk** [comment]
That should probably be precomputed…

**Comment by colorhook** [comment]
Follow the BitmapData definition in Web Standard,  maintain the pixels by TypeArray in Javascript.
I create Pattern by Vec<u8> dynamically each frame and call `draw_subimage` to draw Image.

**Comment by colorhook** [comment]
in CanvasRenderingContext2D `put_image_data` method, `Image::new` called also:

```
pub fn put_image_data<L>(&mut self, image_data: ImageData, dest_location: L)
                             where L: CanvasImageDestLocation {
    let origin = dest_location.origin();
    let size = dest_location.size().unwrap_or(image_data.size.to_f32());
    let pattern = Pattern::from_image(image_data.into_image());
    let paint_id = self.canvas.scene.push_paint(&Paint::from_pattern(pattern));
    let draw_path = DrawPath::new(Outline::from_rect(RectF::new(origin, size)), paint_id);
    self.canvas.scene.push_draw_path(draw_path);
}
```

**Comment by s3bk** [comment]
Creating an Image from data is expensive, there is nothing one can do about it apart from not doing it.
In the best case the image encoding matches the texture and the trans-coding can be skipped, but that is not implemented yet.

**Comment by colorhook** [comment]
I use caching layer to avoid `.drawImage()` performance issues, thanks!
