### ISSUE TITLE
Release cadence?

### ISSUE THREAD

**Issue by berkus** [servo/pathfinder#453]
I see latest pathfinder version was released 1,5 years ago. I believe there are some changes and fixes accumulated since then. What are the roadmap and release plans for this project?

**Comment by jdm** [comment]
Nobody is actively working on this project as far as I know.

**Comment by berkus** [comment]
Any specific reason for that?

Is this project obsoleted by something? Or just abandoned? Does it look for maintainers?

I basically need one thing - the simd fix released so that it's dependee, `servo/font-kit` would  work on Apple M1 hardware.

**Comment by jdm** [comment]
The main developer is no longer being paid to work on it. @pcwalton Would you mind adding the `cargo publish` team to the appropriate pathfinder crates on crates.io?

**Comment by pcwalton** [comment]
I'm not sure what that means exactly...

**Comment by jdm** [comment]
https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

**Comment by jdm** [comment]
You can see an example of a crate with that group as an owner at https://crates.io/crates/smallvec.

**Comment by zimond** [comment]
at least could we update the crates.io version to a recent commit?

**Comment by berkus** [comment]
@jdm I believe you have enough folks to handle this if @pcwalton is willing to extend publishing rights to that team.

However, if you need any help with the maintenance, I can lend a hand. Maybe even two.

**Comment by jdm** [comment]
@pcwalton Could you finish adding the cargo-publish team to the pathfinder crates so I can publish a new version of pathfinder_simd? It should just require `cargo owner --add github:servo:cargo-publish` for each crate.

**Comment by berkus** [comment]
@pcwalton pretty please? M1 Macs are getting obsoleted soon.

**Comment by pcwalton** [comment]
Done.

**Comment by jdm** [comment]
I have published a new version of pathfinder_simd. Thanks!

**Comment by berkus** [comment]
🕺🏼 thank you all!
