### ISSUE TITLE
Following instructions to run demo fails with "failed to get 'encoding'" with regards to "pdf v0.7.0"

### ISSUE THREAD

**Issue by amortaza** [servo/pathfinder#480]
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   C:\Users\Ace\test\pathfinder\examples\canvas_webgl_minimal\Cargo.toml
workspace: C:\Users\Ace\test\pathfinder\Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   C:\Users\Ace\test\pathfinder\web_canvas\Cargo.toml
workspace: C:\Users\Ace\test\pathfinder\Cargo.toml
    Updating crates.io index
    Updating git repository `https://github.com/pdf-rs/encoding/`
error: failed to get `encoding` as a dependency of package `pdf v0.7.0 (https://github.com/pdf-rs/pdf#249b9b0a)`
    ... which satisfies git dependency `pdf` of package `pathfinder_demo v0.1.0 (C:\Users\Ace\test\pathfinder\demo\common)`
    ... which satisfies path dependency `pathfinder_demo` of package `pathfinder_android_demo v0.1.0 (C:\Users\Ace\test\pathfinder\demo\android\rust)`

Caused by:
  failed to load source for dependency `encoding`

Caused by:
  Unable to update https://github.com/pdf-rs/encoding/#44cafed0

Caused by:
  failed to fetch into: C:\Users\Ace\.cargo\git\db\encoding-b7c0f658ef1ffb49

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok https://github.com/pdf-rs/encoding/ HEAD:refs/remotes/origin/HEAD` (exit code: 128)
  --- stderr
  ERROR: Repository not found.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

**Comment by s3bk** [comment]
A spurious network error?
The encoding repository does exist and the demo builds (on linux).
