### ISSUE TITLE
[Question] Can pathfinder render text on a curved surface like a cylinder?

### ISSUE THREAD

**Issue by lostmsu** [servo/pathfinder#508]
I am looking for a way to display text around user in VR in a manner a curved monitor would do. I understand that pathfinder can easily rasterize text to put on a 3D plane, but is it possible to get nicely rendered text on a wall of a cylinder?

**Comment by s3bk** [comment]
You can probably cheat by computing where each glyph would end up and then draw each glyph on a separate plane.

**Comment by lostmsu** [comment]
That's an excellent idea! It does not exactly solve the ideal case, but might just be good enough, thanks.
