### ISSUE TITLE
Project state

### ISSUE THREAD

**Issue by Zubnix** [servo/pathfinder#530]
What's the state of this project? I've read on different places that his project is essentially dead after Mozilla's layoffs. Lack of any commits or releases since 2020 seems to confirm this?

**Comment by jdm** [comment]
I try to merge PRs that look reasonable, but the project has no main contributors or maintainers who are attempting to drive it.

**Comment by Zubnix** [comment]
Ok that’s clear. It really looked like an awesome project. 💔🪦

**Comment by s3bk** [comment]
It was a research prototype that worked very well, and still works very well.
I expect that the experience from Pathfinder 3 will find its way into the next GPU render engine written in Rust.
So in that way it was successful.
