### ISSUE TITLE
Compile Error on nightly, unknown feature `stdsimd`

### ISSUE THREAD

**Issue by ripytide** [servo/pathfinder#550]
```
error[E0635]: unknown feature `stdsimd`
  --> /pathfinder_simd-0.5.2/src/lib.rs:12:49
   |
12 | #![cfg_attr(pf_rustc_nightly, feature(simd_ffi, stdsimd))]
   |                                                 ^^^^^^^
```

This is similar to the error in the `ahash` crate: https://github.com/tkaitchuck/aHash/issues/200

**Comment by jayvdb** [comment]
The commit removing stdsimd is https://github.com/rust-lang/rust/commit/ea37e8091fe87ae0a7e204c034e7d55061e56790
Relevant tracking issues? https://github.com/rust-lang/rust/issues/27731 and https://github.com/rust-lang/rust/issues/48556

**Comment by jayvdb** [comment]
https://github.com/servo/pathfinder/pull/548 fixes this

**Comment by DraftedDev** [comment]
I still get the error when trying to compile `pathfinder_geometry` with the `pf-text` feature.

**Comment by jayvdb** [comment]
https://github.com/servo/pathfinder/blob/main/geometry/Cargo.toml does not have a `pf-text` feature.

Could you provide a lot of the build failure that you are seeing?

**Comment by DraftedDev** [comment]
Sorry, I meant pathfinder_canvas.
But using the patches described in #313 helps.
(though I still get an ugly linker error)

**Comment by jayvdb** [comment]
hmm That feature compiled file for me on stable and nightly, when building on `main`

**Comment by DraftedDev** [comment]
I should probably re-open #313 again.
But thanks anyways :D

**Comment by attila-lin** [comment]
Will we have a new release?

**Comment by avhz** [comment]
This issue seems to be preventing my docs from being built on docs.rs after a publish.

**Comment by avhz** [comment]
Bumping. 
If the fix is pushed, can a bug fix release be pushed to crates.io ?

**Comment by aujxn** [comment]
This is also causing my builds to fail and is deep into my dependency graphs. If I switch from nightly to stable it fixes it but I need nightly features

**Comment by atouchet** [comment]
A new version of pathfinder_simd was published. This should be fixed now.
