### ISSUE TITLE
Compile Error on nightly, platform_intrinsics - feature has been removed

### ISSUE THREAD

**Issue by MikMikus** [servo/pathfinder#558]
on `main` branch for `1.78.0-nightly (c475e2303 2024-02-28)`

```
error[E0557]: feature has been removed
  --> /home/REDACTED/.cargo/git/checkouts/pathfinder-f0bd20e7aa700f92/cb4eb59/simd/src/lib.rs:11:61
   |
   | ...intrinsics, platform_intrinsics))]
   |                ^^^^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: SIMD intrinsics use the regular intrinsics ABI now

For more information about this error, try `rustc --explain E0557`.
```

related to: https://github.com/servo/pathfinder/issues/550 and https://github.com/servo/pathfinder/pull/548

**Comment by sagudev** [comment]
I think `extern "platform-intrinsic"` block needs to be replaced with ` core_intrinsics` feature and `use std::intrinsics::simd::*;`, I will start working on it tomorrow using https://github.com/model-checking/kani/pull/3052/files as reference.
