### ISSUE TITLE
Please publish a new crates.io release

### ISSUE THREAD

**Issue by Nopey** [servo/pathfinder#563]
Please publish a new version to crates.io, as https://github.com/servo/pathfinder/pull/548 has not yet been released.

Once raqote is able to depend on a version of pathfinder that contains PR 548 changes, their CI pipeline will be fixed:
https://github.com/jrmuizel/raqote/pull/201

**Comment by ntorresalberto** [comment]
Hi, came here for the same reason, a new release would be greatly appreciated.
Adding a log output of the error to help visibility (this is with the nightly toolchain):
```
error[E0557]: feature has been removed
  --> /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_simd-0.5.2/src/lib.rs:11:61
   |
11 | ...vm_intrinsics, platform_intrinsics))]
   |                   ^^^^^^^^^^^^^^^^^^^ feature has been removed
   |
   = note: SIMD intrinsics use the regular intrinsics ABI now

   Compiling rand v0.8.5
error[E0635]: unknown feature `stdsimd`
  --> /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/pathfinder_simd-0.5.2/src/lib.rs:12:49
   |
12 | #![cfg_attr(pf_rustc_nightly, feature(simd_ffi, stdsimd))]
   |                                                 ^^^^^^^

Some errors have detailed explanations: E0557, E0635.
For more information about an error, try `rustc --explain E0557`.
error: could not compile `pathfinder_simd` (lib) due to 2 previous errors
```

**Comment by atouchet** [comment]
@jdm @mrobinson or whoever has access can #557 be published to crates.io?

**Comment by mrobinson** [comment]
I have just published a new version of `pathfinder_simd`, which I think should unblock https://github.com/jrmuizel/raqote/pull/201.

**Comment by Nopey** [comment]
Perfect, thanks!
