### ISSUE TITLE
Support for different line join and cap styles

### ISSUE THREAD

**Issue by dylanede** [servo/pathfinder#61]
I'm primarily interested in round joins and caps, but this issue could serve for discussion about line joins and caps in general.

Regarding round joins and caps, would it be better to do those in a separate pass? Each join/cap could be set up as a quad with vertex attributes specifying the normalised coordinates from the centre of the circle, and the pixel shader would check whether the interpolated 2d coordinate is inside the circle (i.e. magnitude less than one). I'm interested in implementing this at some point, and I think it might end up more performant in my use cases than encoding each join/cap as a set of quadratic curves, which could end up with a high density of triangles. I'm not too sure how this technique would interact with the existing anti-aliasing techniques in use in pathfinder as I'm not yet familiar with how XCAA works.

I'm also interested in supporting line dash patterns, though that's best left for another issue.

**Comment by pcwalton** [comment]
In general I think we need to decompose round joins and caps into quadratic Béziers for batching purposes: if we have a complex SVG with lots of overlapping strokes and fills, then we don't want to incur batch breaks every time we switch from stroke to fill. (These batch breaks make a lot of other GPU vector graphics rendering algorithms slow.) It would theoretically be possible to work around this with an ubershader, but I think that'd get pretty ugly. Seems better to just decompose into Béziers.

However, I'm not opposed to having opt-in fast paths for stroke styles that can be used whenever it's deemed better to have the batch break than to incur the overhead of decomposing into Bézier curves. So if you want to write special shaders for those and submit them, feel free; it's just that I think we should have the normal case be Bézier decomposition.

**Comment by pcwalton** [comment]
Implemented for quite a while now
