### ISSUE TITLE
Document the fill algorithm

### ISSUE THREAD

**Issue by eliasnaur** [servo/pathfinder#96]
I'm writing a portable UI library in Go and trying to replicate the fast and high-quality font rendering from Pathfinder. In the [Stencil AAA](https://github.com/pcwalton/pathfinder/commit/a84b7c7cbde7383187838af8673c46fea7532411) commit, there's a tantalizing "Blog posts forthcoming."; alas, I have found no such posts about the algorithm.

I would really appreciate a short, high-level description of how the algorithm works, in particular the theory behind the stencil-aaa.*.glsl shader pair. Also, is it correct that it requires no tesselation (I only see "stencil_segments" and, for stem dilation, "stencil_normals" used)?

**Comment by pcwalton** [comment]
@nical is working on this.

**Comment by eliasnaur** [comment]
Nice! The UI library in question is [Gio](https://gioui.org), where I use a variant of Pathfinder 2. I look forward to switching to Pathfinder 3 when the documentation is ready.

**Comment by pcwalton** [comment]
Here's some documentation: https://nical.github.io/posts/a-look-at-pathfinder.html

Obviously we could get better documentation, but the question has basically been answered so I'm going to close this :)
